# Generated by Django 2.0.6 on 2018-07-01 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='STS9', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('S1', 'Set 1'), ('S2', 'Set 2'), ('S3', 'Set 3'), ('E1', 'Encore'), ('E2', 'Encore 2'), ('AX', 'Axe The Cables'), ('PA', 'PA Set')], default='S1', max_length=2)),
                ('set_pos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_key', models.CharField(max_length=7)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ShowSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.IntegerField()),
                ('segue', models.CharField(max_length=4, null=True)),
                ('notes', models.CharField(max_length=128, null=True)),
                ('guest', models.CharField(max_length=64, null=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setlists.Show')),
                ('show_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setlists.Set')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setlists.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=4, null=True)),
                ('country', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='showsong',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setlists.Song'),
        ),
        migrations.AddField(
            model_name='show',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='setlists.Tour'),
        ),
        migrations.AddField(
            model_name='show',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='setlists.Venue'),
        ),
        migrations.AddField(
            model_name='set',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setlists.Show'),
        ),
    ]
