# Generated by Django 2.0.6 on 2018-07-01 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showsong',
            old_name='show_set',
            new_name='set',
        ),
    ]
