# Generated by Django 2.1.2 on 2018-10-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0002_auto_20180701_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showsong',
            name='segue',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
