# Generated by Django 2.1.2 on 2018-10-23 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setlists', '0003_auto_20181022_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shows', models.ManyToManyField(blank=True, to='setlists.Show')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='showlist',
            name='shows',
        ),
        migrations.RemoveField(
            model_name='showlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='ShowList',
        ),
    ]
