# Generated by Django 2.1.2 on 2018-10-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0003_auto_20181015_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='show',
            field=models.ManyToManyField(to='setlists.Show'),
        ),
    ]
