# Generated by Django 2.1.2 on 2018-10-24 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0004_auto_20181023_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['-date']},
        ),
    ]
