# Generated by Django 2.1.2 on 2018-10-15 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0005_auto_20181015_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='songs',
            field=models.ManyToManyField(null=True, to='setlists.Song'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
