# Generated by Django 2.1.2 on 2018-10-26 20:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('setlists', '0005_auto_20181024_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={},
        ),
    ]
