# Generated by Django 2.1.3 on 2018-12-02 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0006_auto_20181026_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showsong',
            options={'ordering': ['-show__date', 'track']},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['name']},
        ),
    ]
