# Generated by Django 2.1.2 on 2018-10-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0006_auto_20181015_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='songs',
            field=models.ManyToManyField(to='setlists.Song'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
