# Generated by Django 2.1.4 on 2018-12-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0007_auto_20181202_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='showsong',
            name='axed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
