# Generated by Django 2.1.2 on 2018-10-15 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0007_auto_20181015_0323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='songs',
        ),
    ]
