# Generated by Django 2.1.4 on 2018-12-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0008_showsong_axed'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='notes',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
