# Generated by Django 2.1.2 on 2018-10-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0008_remove_show_songs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='show',
        ),
        migrations.AlterField(
            model_name='showsong',
            name='set',
            field=models.CharField(choices=[('S1', 'Set 1'), ('S2', 'Set 2'), ('S3', 'Set 3'), ('E1', 'Encore'), ('E2', 'Encore 2'), ('AX', 'Axe The Cables'), ('PA', 'PA Set')], default='S1', max_length=2),
        ),
        migrations.DeleteModel(
            name='Set',
        ),
    ]
