# Generated by Django 2.1.2 on 2018-10-15 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0009_auto_20181015_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='show_key',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='show',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='setlists.Tour'),
        ),
        migrations.AlterField(
            model_name='showsong',
            name='guest',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='showsong',
            name='notes',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='showsong',
            name='segue',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='state',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
