# Generated by Django 2.1.5 on 2019-03-30 21:02

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0009_show_notes'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='venue',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
