# Generated by Django 2.1.2 on 2018-10-15 15:40

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0010_auto_20181015_0424'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='show',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
