# Generated by Django 2.1.2 on 2018-10-18 17:37

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0011_auto_20181015_0940'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='song',
            managers=[
                ('data', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='showsong',
            name='set',
            field=models.CharField(choices=[('S1', 'Set 1'), ('S2', 'Set 2'), ('S3', 'Set 3'), ('E1', 'Encore'), ('E2', 'Encore 2'), ('AX', 'Axe The Cables'), ('PA', 'PA Set'), ('W1', 'Wave Spell 1'), ('W2', 'Wave Spell 2')], default='S1', max_length=2),
        ),
    ]
