# Generated by Django 2.1.2 on 2018-10-19 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0012_auto_20181018_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showsong',
            options={'ordering': ['track']},
        ),
    ]
